version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./init-aws.sh:/usr/local/bin/init-aws.sh
    command: /bin/sh -c "/usr/local/bin/init-aws.sh"

  service1:
    build: ./services/service1
    env_file: .env
    depends_on:
      - localstack

  service2:
    build: ./services/service2
    env_file: .env
    depends_on:
      - localstack

  service3:
    build: ./services/service3
    env_file: .env
    depends_on:
      - localstack
